name: ngpu-original
dependencies:
        - joblib
        - matplotlib=2.0
        - tensorflow=0.10.0rc0  # oldest version available in conda
        - pandas
        - python
        - pyyaml
        - scipy
